# Generated by Django 5.0.6 on 2024-07-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junior', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='isbn',
            field=models.IntegerField(),
        ),
    ]
